github: @FabianaCampanari
['https://github.com/FabianaCampanari',
'https://github.com/FabianaCampanari/University-Grades-Tracker']
open_collective: @FabianaCampanari
['https://opencollective.com/fabianacampanari', 
'https://opencollective.com/fabianacampanari/projects/university-grades-tracker']
